build.sbt
src/main/scala/io/findify/s3mock/provider/FileProvider.scala
src/main/scala/io/findify/s3mock/provider/Provider.scala
src/main/scala/io/findify/s3mock/route/GetObject.scala
src/main/scala/io/findify/s3mock/route/PutObject.scala
src/test/scala/io/findify/s3mock/GetPutObjectWithMetadataTest.scala
src/test/scala/io/findify/s3mock/ListBucketEmptyWorkdirTest.scala
src/test/scala/io/findify/s3mock/ListBucketTest.scala

The listBucket method returns list of entries with invalid keys.
The given keys contain an leading "/" which has to be dropped to query the object.
Add metadata support.

listBucket returns invalid keys ('/' in front); add support for metadata

---

README.md

Inconveniently, Scala distinguishes a method without parentheses and a method with empty parentheses.
http://stackoverflow.com/questions/7409502/what-is-the-difference-between-def-foo-and-def-foo-in-scala

fix a method call in README

---

src/main/scala/io/findify/s3mock/error/InternalErrorException.scala
src/main/scala/io/findify/s3mock/error/NoSuchBucketException.scala
src/main/scala/io/findify/s3mock/provider/FileProvider.scala
src/main/scala/io/findify/s3mock/route/CopyObject.scala
src/main/scala/io/findify/s3mock/route/DeleteBucket.scala
src/main/scala/io/findify/s3mock/route/GetObject.scala
src/main/scala/io/findify/s3mock/route/ListBucket.scala
src/main/scala/io/findify/s3mock/route/PutObject.scala
src/main/scala/io/findify/s3mock/route/PutObjectMultipart.scala
src/main/scala/io/findify/s3mock/route/PutObjectMultipartComplete.scala
src/main/scala/io/findify/s3mock/route/PutObjectMultipartStart.scala
src/test/scala/io/findify/s3mock/DeleteTest.scala
src/test/scala/io/findify/s3mock/GetPutObjectTest.scala
src/test/scala/io/findify/s3mock/ListBucketTest.scala
src/test/scala/io/findify/s3mock/MultipartUploadTest.scala
src/test/scala/io/findify/s3mock/awscli/GetObjectTest.scala

When I created unit tests with S3 mock I realised that **NoSuchBucket** error is not thrown when the bucket (underlying folder) does not exists in case of `getObject` and `putObject`. These calls returned with `NoSuchKey` which was misleading for me, becuase the official S3 enpoints produce `NoSuchBucket`. I wanted to created 2 separate unit tests one for `NoSuchBucket` and one for `NoSuchKey`
Add XML representation of error message to the already existing `NoSuchBucketException` class and throw `NoSuchBucket` error if the bucket does not exist in the following cases:
- GetObject
- PutObject
- PutObjectMultipart
- ListBucket
- DeleteBucket
- New unit tests for `NoSuchBucket` errors.

Throw NoSuckBucket error if bucket does not exist

---

build.sbt
src/test/scala/io/findify/s3mock/GetPutObjectTest.scala
src/test/scala/io/findify/s3mock/GetPutObjectWithMetadataTest.scala
src/test/scala/io/findify/s3mock/JavaExampleTest.scala
src/test/scala/io/findify/s3mock/MultipartUploadTest.scala
src/test/scala/io/findify/s3mock/S3MockTest.scala
src/test/scala/io/findify/s3mock/transfermanager/PutGetTest.scala

When I checked the unit tests I faced that Apache Commons IO is used to play with inputstream/byte arrays in the following way: 
`IOUtils.toString(s3.getObject("getput", "foo2").getObjectContent, Charset.forName("UTF-8"))`
Using the standard Scala [Source](http://www.scala-lang.org/api/2.12.0/scala/io/Source$.html#fromInputStream(is:java.io.InputStream,enc:String):scala.io.BufferedSource) class, the previous line can be rewritten as:
`Source.fromInputStream(s3Object.getObjectContent, "UTF-8").mkString`
Which is a bit easier to read and relies on a standard library solution instead of an external dependency. I created a `getContent` method to remove code duplications which uses the Source class to get the content of an S3 object.
Commons IO was used only in tests, so the dependency was …

Use stanard Source class instead of Apache Commons IO in tests

---

src/main/scala/io/findify/s3mock/S3Mock.scala
src/main/scala/io/findify/s3mock/route/GetObject.scala
src/test/scala/io/findify/s3mock/GetPutObjectTest.scala

Added a few hooks to provide some primitive support for amazon's object tagging.
Supports writing tags with a PutObjectRequest (does NOT support setObjectTagging).
Supports reading tags with getObjectTagging.
Added because I'm using (and love) s3mock to test my s3 code, but I need to test my tagging code as we're starting to use tagging to do some billing tracking.
Also I didn't bump the version number as I figured you'd want to do that if/when you merge this.

Enable basic object tagging support

---

src/main/scala/io/findify/s3mock/Main.scala
src/main/scala/io/findify/s3mock/S3ChunkedProtocolStage.scala
src/main/scala/io/findify/s3mock/S3Mock.scala
src/main/scala/io/findify/s3mock/provider/FileProvider.scala
src/main/scala/io/findify/s3mock/route/GetObject.scala
src/test/resources/application.conf
src/test/scala/io/findify/s3mock/GetPutObjectTest.scala
src/test/scala/io/findify/s3mock/JavaExampleTest.scala
src/test/scala/io/findify/s3mock/ListBucketEmptyWorkdirTest.scala
src/test/scala/io/findify/s3mock/MapMetadataStoreTest.scala
src/test/scala/io/findify/s3mock/S3MockTest.scala

Added ability to retrieve part of S3 object by supplying byte range in `Range` header of `GET` request.
Performed minor cleanup changes.

Ranged get requests support

---

src/main/scala/io/findify/s3mock/S3Mock.scala
src/main/scala/io/findify/s3mock/provider/InMemoryProvider.scala
src/main/scala/io/findify/s3mock/provider/metadata/InMemoryMetadataStore.scala
src/test/scala/io/findify/s3mock/CopyObjectTest.scala
src/test/scala/io/findify/s3mock/DeleteTest.scala
src/test/scala/io/findify/s3mock/GetPutObjectTest.scala
src/test/scala/io/findify/s3mock/GetPutObjectWithMetadataTest.scala
src/test/scala/io/findify/s3mock/JavaExampleTest.scala
src/test/scala/io/findify/s3mock/ListBucketEmptyWorkdirTest.scala
src/test/scala/io/findify/s3mock/ListBucketTest.scala
src/test/scala/io/findify/s3mock/ListBucketsTest.scala
src/test/scala/io/findify/s3mock/MapMetadataStoreTest.scala
src/test/scala/io/findify/s3mock/MultipartUploadTest.scala
src/test/scala/io/findify/s3mock/PutBucketTest.scala
src/test/scala/io/findify/s3mock/S3MockTest.scala
src/test/scala/io/findify/s3mock/awscli/GetObjectTest.scala
src/test/scala/io/findify/s3mock/awscli/PutBucketTest.scala
src/test/scala/io/findify/s3mock/transfermanager/PutGetTest.scala

This is an attempt to implement the in-memory backend mentioned in https://github.com/findify/s3mock/issues/25 . I believe it to be complete (on the same level as `FileProvider`, but am happy to work on/rework any part of it, or abandon it altogether should another solution be preferable.
In terms of the behaviour, it should be mostly identical with the existing `FileProvider`, apart from:
- will calculate md5sums for `ListBucket` requests. `FileProvider` seems to return `0` for all.
- will throw `NoSuchBucketException` when a delete request is received against a nonexistent bucket. `FileProvider` throws `NoSuchKeyException` only. The correct semantics are unclear to me.
- does not care about about separators and doesn't need to strip leading slashes, as it's not bound to the file system …

In-Memory Provider for Object and Metadata storage

---

src/main/scala/io/findify/s3mock/route/PutObjectMultipart.scala
src/main/scala/io/findify/s3mock/route/PutObjectMultipartComplete.scala
src/main/scala/io/findify/s3mock/route/PutObjectMultipartStart.scala
src/test/scala/io/findify/s3mock/S3MockTest.scala
src/test/scala/io/findify/s3mock/alpakka/GetObjectTest.scala
src/test/scala/io/findify/s3mock/alpakka/MultipartUploadTest.scala

This fixes #61
I added the correct response content-types for start and stop of the the multipart API which are checked hard by Alpakka. The Amazon S3 client does not seem to check these and the docs don't specify them. All tests are running so it seems this works. 
Also ETags in the responses from the Multipart Part Uploads are mandatory by Alpakka. I added these.
Currently S3Mock assumes that on an authenticated request the content is always chunked. This is only true for the Amazon SDK S3 client but not for Alpakka S3. 
The docs state that chunking is optional for clients (http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html).
I added a detection based on the header `x-amz-decoded-content-length` which is only present when the content is (chunk-)encoded. Based on this …

Support Alpakka multipart uploads

---

README.md

Since we need to be able to access the s3mock classes, we need a jar dependency and not the pom dependency

Remove pom dependency type

---

src/main/scala/io/findify/s3mock/response/CompleteMultipartUploadResult.scala
src/main/scala/io/findify/s3mock/response/InitiateMultipartUploadResult.scala

fixes https://github.com/findify/s3mock/issues/77 by decoding the key before sending it back to the caller.

Fix encoding problem which leads to mulitpart upload failure in alpakka s3 when using % in key name

---

build.sbt

Java 9 doesn't consider JAXB part of Java EE APIs as explained here (https://stackoverflow.com/a/43574427/38483). 
Without that extra parameter we get this exception when running the docker image:
```
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
... 70 more
```

Provide access to JAXB when using Java 9

---

README.md
src/main/scala/io/findify/s3mock/Main.scala

This feature enables the users of the Docker image to serve prepared directory contents by mounting a Docker volume and setting an environment variable.

Docker: Allow serving a prepared directory

---

build.sbt

The error is this when doing GetObject on a pre-existing file of a pre-existing bucket:
```
java.nio.channels.OverlappingFileLockException: null
at java.base/sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
at java.base/sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1121)
at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1160)
at org.iq80.leveldb.impl.DbLock.<init>(DbLock.java:47)
at org.iq80.leveldb.impl.DbImpl.<init>(DbImpl.java:167)
at org.iq80.leveldb.impl.Iq80DBFactory.open(Iq80DBFactory.java:82)
at io.findify.s3mock.provider.metadata.MapMetadataStore.load(MapMetadataStore.scala:50)
at io.findify.s3mock.provider.metadata.MapMetadataStore.get(MapMetadataStore.scala:26)
at …
```

[83] Patch OverlappingFileLockException in GetObject.

---

src/main/scala/io/findify/s3mock/route/DeleteObjects.scala
src/test/java/io/findify/s3mock/example/JavaBuilderExample.java

Fixes https://github.com/findify/s3mock/issues/166.

DeleteObjects should encode object key like single-object APIs

---

README.md

Version 0.2.4 does not have the shutdown method as described in README.md

fixes release version to latest in README

---

src/main/scala/io/findify/s3mock/provider/FileProvider.scala

This allows for a prepolated s3 bucket without copying potentially large files.

Follow symlinks in FileProvider

---

src/main/scala/io/findify/s3mock/provider/FileProvider.scala

Small mistake when creating md5 sum, the close is missing from FileInputStream.
This causes to run the process out of file descriptors when listing buckets with a couple thousand files.

File descriptor leak in list bucket

---

src/main/scala/io/findify/s3mock/provider/FileProvider.scala
src/main/scala/io/findify/s3mock/route/GetObject.scala
src/test/scala/io/findify/s3mock/awscli/GetObjectTest.scala

By default when we had metadata, header `Last-Modified` was being returned twice:
```
curl -I -X GET localhost:8001/mybucket/hello.txt
HTTP/1.1 200 OK
Accept-Ranges: bytes
Last-Modified: Thu, 01 Jan 1970 00:00:00 GMT
Last-Modified: Thu, 21 Jun 2018 11:44:44 GMT
Timeout-Access: <function1>
Expect: 100-continue
Content-MD5: d41d8cd98f00b204e9800998ecf8427e
Accept-Encoding: identity
User-Agent: aws-cli/1.15.41 Python/3.6.5 Linux/4.15.0-23-generic botocore/1.10.41
Host: localhost:8001
ETag: d41d8cd98f00b204e9800998ecf8427e
Server: akka-http/10.1.0
Date: Thu, 21 Jun 2018 11:45:13 GMT
Content-Type: text/plain
Content-Length: 0
```
Making some functions from the boto3 library fail with an exception because it is trying to parse as a date the concatenation of those two dates:
```
In [100]: …
```

Do not duplicate Last-Modified header

---

src/main/scala/io/findify/s3mock/route/PutObject.scala

It happened that the condition for using chuking processing when doing a PutObject was the check for `authorization` header in the request. But this was creating some false positives with Python library boto3 when using it like:
```
client.upload_fileobj(BytesIO("hello world".encode("utf-8")), "mybucket", "test.txt")
```
Reading documentatoin in https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html it is clear that for chunked content one of the required headers is `x-amz-decoded-content-length` that is more unequivocal.
This PR is aiming at keeping the functionality as is (JavaExampleTest.scala keeps working) but at the same time make it interoperate with boto3.

Pick a more discriminative header for chunked content

---

src/main/scala/io/findify/s3mock/provider/FileProvider.scala
src/main/scala/io/findify/s3mock/provider/InMemoryProvider.scala
src/main/scala/io/findify/s3mock/provider/Provider.scala
src/test/scala/io/findify/s3mock/ListBucketTest.scala

In most of Python libraries like boto3, when listing contents of a bucket, an empty string as delimiter is considered as not provided (see for instance [Apache Airflow](https://github.com/apache/incubator-airflow/blob/master/airflow/hooks/S3_hook.py#L118)). Also when using the `boto3` library this 2 calls are semantically equivalent and return all keys under the bucket:
```
boto3.client('s3', region_name='eu-west-1').list_objects_v2(Bucket="mybucket")
```
and
```
boto3.client('s3', region_name='eu-west-1').list_objects_v2(Bucket="mybucket", Prefix='', Delimiter='')
```
But in S3Mock whenever you provide a string, it becomes `Some("")` as the delimiter and returns nothing. Since it doesn't make much sense to have an empty string as delimiter, I've created this PR to transform that into …

Fix empty delimiter string not being considered as None

---

build.sbt

Resolves an issue where "java.lang.IllegalAccessException: class org.iq80.leveldb.util.ByteBufferSupport cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module" when trying to put stream objects.
Fixes https://github.com/findify/s3mock/issues/168

fix java 11 module issue
